### ISSUE TITLE
`highlight(roll, default, tooltip)` incompatible with 3D roll hack

### ISSUE THREAD

**Issue by phylll** [michael-buschbeck/mychs-macro-magic#108]
Turns out, if I'm not overlooking something, that the new `highlight(roll, default, tooltip)` helps in practice only with either static rolls or silent rolls using `roll()`, but not if rolls are reconstructed from a vanilla 3D roll, because the manipulation of the roll result kills the roll struct -- typical code fragment from one of various scripts:

```
&{template:none} [[1d20]] {{}}
!mmm   set attackRoll = $[[0]]
!mmm   set attackResult = attackRoll + effAttack + modifiers
!mmm   set attackResultLog = attackResult & " = (1d20 = " & attackRoll & ") + (EW = " & effAttack & ") + (" & modifiers & ")"
!mmm   if iscritical(attackRoll)
!mmm     set attackResult = highlight(attackResult, "good", attackResultLog)
!mmm   else if isfumble(attackRoll)
!mmm     set attackResult = highlight(attackResult, "bad", attackResultLog)
!mmm   else 
!mmm     set attackResult = highlight(attackResult, "normal", attackResultLog)
!mmm   end if
```

Here, I'm still keeping that `if..else..else` tree because `attackResult` is no longer a roll, but a simple number. I don't think there is currently a way of manipulating a roll struct, is there?

This isn't a problem as such, since the above code works.

**Comment by michael-buschbeck** [comment]
#7 had originally proposed supporting that *a roll* could be passed as the `type` parameter to `highlight()` – so you could write `highlight(attackResult, attackRoll, tooltip)` as a shorthand for the `if` construct above.

Would that work?

**Comment by phylll** [comment]
Yes, it absolutely would work.

**Comment by michael-buschbeck** [comment]
Given that it has meanwhile become possible to create custom functions... is this still relevant?

```
!mmm function highlightType(roll)
!mmm     set critical = iscritical(roll)
!mmm     set fumble = isfumble(roll)
!mmm     if critical and fumble
!mmm         return "important"
!mmm     else if critical
!mmm         return "good"
!mmm     else if fumble
!mmm         return "bad"
!mmm     end if
!mmm     return "normal"
!mmm end function
```

**Comment by phylll** [comment]
Indeed. I've since implemented a similar solution to the one you're suggesting. Closing this issue.
