### ISSUE TITLE
Parser issue with ?[??]

### ISSUE THREAD

**Issue by phylll** [michael-buschbeck/mychs-macro-magic#124]
In this scriptlet (use in TEST game), both `?` and `???` fail to resolve the entire variable that follows (`foe.Gw`) and rather just resolve to `foe`:

```
!mmm script
!mmm   set foe = "-MS7W5j56aYtw9Ry4vZV"
!mmm   if isunknown(??? foe.Gw)
!mmm       chat: /w GM ${foe.name} erlaubt keinen Zugriff auf das Attribut **Gw**. 
!mmm   end if
!mmm end script
```

Output (regardless whether I use one or two or three question marks):

```
🔎 "-MS7W5j56aYtw9Ry4vZV" ◀️ isunknown(??? foe.Gw)
```

**Comment by michael-buschbeck** [comment]
This, oddly enough, happens only in parentheses. I'm looking into it.
