### ISSUE TITLE
Inconsistent problem with access to "target" data

### ISSUE THREAD

**Issue by phylll** [michael-buschbeck/mychs-macro-magic#13]
Access to `target` data is inconsistent for me: the initial call always results in a prompt to designate the target, but every later retrieval of data works only sometimes (on some instances of running the same code, and then consistently over the course of the script), while other times (running the same code, designating the same or different tokens as targets) I get empty data.

Using something like `@{target|x|character_name}` in the chat outside mmm seems to work consistently well.

My main use case so far is this:

> !mmm script
> !mmm   set myName = getattr(sender, "character_name")
> !mmm   set effAttValueMagicSword = getattr(sender, "effAngriffLangschwert")
> !mmm   set foeName = "@{target|t1|character_name}"
> !mmm   set boni = ?{Angriffsboni/-mali|0}
> !mmm   set roll = [[1d20]]
> !mmm   set result = roll + effAttValueMagicSword + boni
> !mmm   set damage = [[1d6]] + getattr(sender, "effSchadenLangschwertFeuer") 
> !mmm
> !mmm   if foeName eq ""                        // added as a workaround for the cases where foeName comes out empty
> !mmm     set foeName = "Namenlose:r Fiesling"
> !mmm   end if
> !mmm   combine chat
> !mmm     chat: *Ich gehe mit meiner magischen Klinge auf **${foeName}** los 
> ... (and so worth cycling through different results of the roll`

**Comment by michael-buschbeck** [comment]
Thanks for filing this! I'll have a look at once.

Side note: You're just made me realize I haven't added a facility for *comments* to MMM. To be fair, you could probably just write "!rem blah" to the same effect ;)

**Comment by michael-buschbeck** [comment]
This boils down to MMM being more restrictive than Roll20 itself regarding access to `character_name`.

Strictly speaking you shouldn't be able to see it unless you have access to the character sheet, but Roll20 makes an exception for `@{target|x|character_name}` and `@{selected|character_name}` assuming you can see the *token's* name (which is guaranteed to be the same as the character's).

MMM should make the same exception.

**Comment by michael-buschbeck** [comment]
Also, unrelated, Roll20 has a bug where `@{target|x|character_name}` reveals a token's name even when it's not visible to players – specifically when `showname` is true but `showplayers_name` is false. Since this combination hides the nameplate from players, it stands to reason that the name shouldn't be accessible.

To be fair, [documentation on the matter](https://help.roll20.net/hc/en-us/articles/360037772793-API-Objects#API:Objects-Graphic\(Token/Map/Card/Etc.\))is rather vague, So there's no way of telling what *is* intended behavior.
