### ISSUE TITLE
API disables script that attempts write access to another (controllable) character sheet

### ISSUE THREAD

**Issue by phylll** [michael-buschbeck/mychs-macro-magic#143]
So I'm not sure this is what happens, because it's not straightforward to isolate the problem, or at least I'm confused by it. What appears to happen is that once I add the following few lines to the otherwise well-tested `meleeAttack` script, whenever the attack succeeds and results in positive damage, something called `firebase` throws an exception that makes the API disable all our scripts, and the script dies without producing any output, debug or otherwise. Restarting the sandbox helps, but the lack of debug output makes it difficult to investigate further.

Here's the offensive code:
```!mmm   set m3mgdExchange = getattr("MacroSheet", "character_id")
!mmm   set m3mgdAttrAttackType = "m3mgd_attack_type"
!mmm   set m3mgdAttrAttackerID = "m3mgd_attack_attackerID"
!mmm   set m3mgdAttrAttackTargetID = "m3mgd_attack_targetID"
!mmm   set m3mgdAttrAttackResult = "m3mgd_attack_result"
!mmm   set m3mgdAttrAttackDamage = "m3mgd_attack_damage"
[...]
!mmm   if attackResult >= 20 and damageResult > 0
!mmm     do setattr(m3mgdExchange, m3mgdAttrAttackType, "melee")
!mmm     do setattr(m3mgdExchange, m3mgdAttrAttackerID, cOwnId)
!mmm     do setattr(m3mgdExchange, m3mgdAttrAttackTargetID, foeId)
!mmm     do setattr(m3mgdExchange, m3mgdAttrAttackResult, attackResult)
!mmm     do setattr(m3mgdExchange, m3mgdAttrAttackDamage, damageResult)
!mmm   end if
```

Here's the error message from the TEST log:
```Your scripts are currently disabled due to an error that was detected. Please make appropriate changes to your script's code and click the "Save Script" button. We will then attempt to start running the scripts again. More info... If this script was installed from the Script Library, you might find help in the Community API Forum.

For reference, the error message generated was: Error: Firebase.update failed: First argument contains undefined in property 'current'
Error: Firebase.update failed: First argument contains undefined in property 'current'
    at Ba (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:9:49)
    at Ba (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:10:207)
    at Aa (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:8:462)
    at Ea (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:10:403)
    at J.update (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:146:318)
    at TrackedObj._doSave (/home/node/d20-api-server/api.js:905:27)
    at Timeout.later [as _onTimeout] (/home/node/d20-api-server/node_modules/underscore/underscore-umd.js:1153:39)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by phylll** [comment]
Oh, right: I am executing the script as `phyllo (GM)`, and the character sheet `MacroSheet` allows `control` by all players. When I test this for myself using

`!mmm chat: ${"MacroSheet".permission}`,

then I get the expected output:

`control`

**Comment by phylll** [comment]
One thing that sets `MacroSheet` apart from other character sheets that do not belong to myself and that I *have* been able to write into: `MacroSheet` does not have a token that is present anywhere on the "board".

**Comment by phylll** [comment]
Linking `MacroSheet` with a visible token doesn't help, either.

**Comment by michael-buschbeck** [comment]
After a fruitful pair debugging session over Skype it turns out that the problem is a mistyped MMM variable that led to MMM attempting to write JavaScript `undefined` as the attribute's value.

Seems like MMM should be writing `null` in place of `undefined`.
