### ISSUE TITLE
Allow scripts to manipulate `sender` for chat output

### ISSUE THREAD

**Issue by phylll** [michael-buschbeck/mychs-macro-magic#146]
To reduce confusion when the same scripts are executed shortly after one another by the GM for a number of NPCs, it would be great to be able to have a script speak as different NPCs rather than only as the user that called it (the GM, in this case).

This blocks phylll's [issue no. 22](https://github.com/phylll/mychs-macro-magic/issues/22).

**Comment by michael-buschbeck** [comment]
Plan:
- Support function overload `chat(nameOrId, message)` in addition to the existing `chat(message)`. Requires that the user has control permission for the given `nameOrId`, or else MMM will simply ignore `nameOrId` and speak as the original sender anyway.
- Extend the `!mmm chat:` command (which internally uses the `chat()` function) to check whether a `sender` variable is set in the variable stash, and if so, pass its value as to the `chat()` function as its first argument.
- Update the `!mmm combine chat` command to a) store the first `nameOrId` passed to its internal temporary `chat()` override and 2) pass it on to the original `chat()` function.
