### ISSUE TITLE
Provide access to table scale

### ISSUE THREAD

**Issue by michael-buschbeck** [michael-buschbeck/mychs-macro-magic#15]
The `left` and `top` attributes are given in (unzoomed) pixels, but sometimes (or even most often?), in-game are of greater interest.

Provide a way to convert between pixels and in-game dimensions.

**Comment by michael-buschbeck** [comment]
Table scale is available through the `page` object API ([see docs](https://help.roll20.net/hc/en-us/articles/360037772793-API-Objects#API:Objects-Page)) as these two properties:
- `scale_number`
- `scale_units` – one of `ft` `m` `km` `mi` `in.` `cm` `un.` `hex` `sq.` or any custom label

I was thinking to provide conversion support (e.g. "give me these dimensions in meters" even if the page is measured in feet), but given the availability of under- and undefined units that may not be possible. (But I can still convert from pixels to "map units" and back and also provide access to the map unit name itself.)

**Comment by phylll** [comment]
Thanks! I think it makes sense to assume that the page is measured in the unit we need for whatever the macros do that are executed on that page -- if we're fighting according to Midgard rules which work in meters, the GM will scale the page in meters since otherwise we won't be able to use the Roll20 measurement tool to understand distances correctly. These might vary within the same game, e.g. meters for combat and kilometers for overland travel. So if MMM gave me access to the conversion factor between pixels and the current `scale_unit`, that would seem completely sufficient!

**Comment by phylll** [comment]
There appears to be also a `page` property called `snapping_increment` which seems to be useful in this regard, see https://app.roll20.net/forum/post/9007178/help-getting-token-coordinates-using-selected-and-target/?pageforid=9007685#post-9007685

**Comment by michael-buschbeck** [comment]
Interesting… so the `scale` properties are in units of `snapping_increment` (times grid unit = 70 pixels)?

Gotta play around with those settings to get a grip on this.

**Comment by michael-buschbeck** [comment]
> So if MMM gave me access to the conversion factor between pixels and the current `scale_unit`, that would seem completely sufficient!

Yeah, that makes sense.

I'll do that and provide the unit separately for good measure – if anyone wants to convert feet to meters, they can do it themselves.

**Comment by michael-buschbeck** [comment]
Playing around yields this insight (consistent with the forum posting linked above):

- A "grid cell" (or "grid space") has width and height of 70px times `snapping_increment`
- `scale_number` gives the number of units per grid cell
- `scale_unit` is purely visual

So:

- units = pixels * `scale_number` / (70 * `snapping_increment`)
- pixels = units * (70 * `snapping_increment`) / `scale_number`

The docs are significantly confused about what constitutes a "unit" and what a "grid cell" – the interpretation that matches observation is that a "unit" is fixed at 70px, which however makes the documentation of `scale_number` wrong ("distance of one unit" – no, of one ***grid cell***).

**Comment by michael-buschbeck** [comment]
Slight twist: If the GM disables snapping, `snapping_increment` gets set to zero, but distances act as if it was `1`.
