### ISSUE TITLE
Support "table" or "key-value" data

### ISSUE THREAD

**Issue by michael-buschbeck** [michael-buschbeck/mychs-macro-magic#159]
There's mounting desire to have native support for a "table" or "key-value" data type in MMM:

Quoting [this comment](https://github.com/michael-buschbeck/mychs-macro-magic/issues/9#issuecomment-789551686) from #9 (which was closed after implementing **foreach**):

> Tables seem to be everywhere:
> 
> - Turn tracker: token, label, value
> - Default roll template table: label, value
> - (custom) Gathering ammo: ammoType, ammoName, weaponName
> 
> Tables could also meaningfully double as key-value maps, only that you can potentially look up any table row by any column value or combination thereof (that's where the where clause above would become more like SQL's where).

Plus there's the custom use case of wanting to gather a bunch of attribute-value pairs to be set in one go via `do attrs select setattr(...key, ...value)`.

**Comment by michael-buschbeck** [comment]
Wishlist:

- `struct.foo` to access value in `struct` that has the key `foo`
- Struct fields can be lists, and list elements can be structs (the only way to nest lists in lists)
- Struct fields can be `undef`, which is distinct from the corresponding struct field being absent
- `items(struct)` to make `struct` into a list of its fields, each represented as a struct with `key` and `value` fields
  - `items(non_struct)` returns a single struct with just `value` (no `key`)
  - `items(list_of_structs)` returns a list of structs that each have `index`, `key`, and `value` fields
- Struct fields are enumerated in the order they were initially added

Syntax:

- Key-value pair:
  - `key => value`?
  - `key: value`?
  - `#key value`?
- Any individual key-value pair is a struct already. Saying `{ key => item }` instead of just `key => item` is valid but redundant.
- Construct a struct that has multiple key-value pairs: `{ key => value, key => value }`
- Concatenating structs within `{ }` makes them into a combined struct that contains all keys and values. If a key appears multiple times, the last occurrence is retained, all previous ones discarded.
- Replacing a key-value pair works by simply concatenating the existing struct with the updated key-value pair: `{ struct, key => new_value }`
- Removing a key: `{ items(struct) where ...key ne "key_to_remove" }`...? (Cumbersome, but how often does one actually need to remove a key where simply setting the key to `undef` is not an option?)

Notes:

- No pressing need for `keys(struct)` – can use `items(struct) select ...key` (or probably just `items(struct)` and then access the `key` field at the place of use)

**Comment by michael-buschbeck** [comment]
> - Any individual key-value pair is a struct already. Saying `{ key => item }` instead of just `key => item` is valid but redundant.

There's a use case against that: syntax sugar for named arguments in function calls while still preserving the ability to pass structs to functions.

The "key-value" type should be as internal to the expression engine as the existing "args" type. There are various potential places of egress that must be covered:

- Final evaluation result.
- List element.
- Value of a key-value pair (i.e. key-key-value should be key-struct).

Basically, a key-value pair should be normalized to a single-key struct _except_ when it is added to an "args" list.

**Comment by michael-buschbeck** [comment]
> Is the idea of being able to store and retrieve structs, or rather, stringify and de-stringify structs still part of this? It would be super helpful given the fixed and cumbersome way Roll20 character sheets are designed if I could store limited amounts of structured data in individual attributes, i.e. without building mountains of individual attributes or rollable tables.

With the advent of `!mmm publish to game`, is this still relevant? I imagine you won't use attributes for data exchange anymore.

A disadvantage of that approach would be that the shared/exchanged data wouldn't survive a sandbox crash/restart anymore. Not sure how significant that is.

**Comment by phylll** [comment]
> With the advent of `!mmm publish to game`, is this still relevant? I imagine you won't use attributes for data exchange anymore.

It could be, not for short term data exchange but for permanently storing data that properly belong in character sheets rather than being hardcoded into scripts. Not sure, though, how high a priority this is ... if it's simple (e.g. if you could use some off-the-shelf JS to do it and just give me two functions as an interface), I would like to have it. If it's not so simple, I'd have to think about this some more...

**Comment by michael-buschbeck** [comment]
Requires #187

**Comment by michael-buschbeck** [comment]
> The "key-value" type should be as internal to the expression engine as the existing "args" type. 

No, that's wrong – we could never do `for item in struct...` if that was the case.

The key-value type must be public. A list of key-value pairs has different semantics than a struct (constructed from a list of key-value pairs). The `struct...` functionality can't be made implicit, and the `{`...`}` list constructor also can't be made optional.

The `struct...` syntax to convert a struct to a list of key-value pairs can't be made implicit in list context because then a list of structs behaves inconsistently in list context depending on whether it contains a single element (which is indistinguishable from "just that individual struct" per design decisions made in #102), in which case it would result in a list of its key-value pairs, or multiple elements, in which case it would be regarded as a list of structs.

**Comment by michael-buschbeck** [comment]
Just to leave a note that I haven't been _entirely_ asleep on this...

I've been making headway on making the parser backtrack when necessary and getting it to understand `key: value`, `"key": value`, and `("k"&"ey"): value` – as well as `{`...`}` to make a struct.

Only thing still missing: `struct...` to make a struct into a list of items – MMM's first postfix operator.

Interesting discovery along the way: The `:` operator has a precedence that's best described as "weird" because it binds really tightly to its left-hand side (just the key) and rather loosely on its right-hand side (practically anything just barely shy of `,`).

In any case, the parser is better now for understanding all this.

> Is the idea of being able to store and retrieve structs, or rather, stringify and de-stringify structs still part of this?

It has occurred to me that a MMM expression literal could be _safely_ parsed (without making it an inroad for arbitrary code execution) with help of a MychExpression parser feature I haven't really been using so far: The parser is capable of figuring out if an expression is (fully or partially) _constant_ in the sense that it can be executed without accessing variables, functions, or any other context.

On the other end there's already been built-in functionality to make an MMM value into a MMM expression literal for a while, so far only used to help the `???` and `!mmm debug` features and not _completely_ faithful in that, but that is easily fixed.

So: Imagine a `serialize(value)` function that makes `value` into a string that looks like an MMM expression literal that would evaluate to `value`, and `deserialize(string)` that parses an MMM expression literal provided it is constant.

That should fit the bill, right?

**Comment by phylll** [comment]
Yes, that sounds about perfect!

**Comment by michael-buschbeck** [comment]
`mmmonify(val)` and - wait for it! – `demmmonify(str)`, anyone?

**Comment by phylll** [comment]
🤣 -- I, er, appreciate the pun but unless the MMM update comes with a dictionary for VScode that keeps me from constantly misspelling the number of `m`s, I would respectfully opt for the boring `[de]serialize()` version :-) Also, who wants to `demonize()` their variables, and if they do, shouldn't the counterspell be called `exorcize()`? 😜

**Comment by michael-buschbeck** [comment]
Final struct expression syntax elements:

Key-value pairs
---
`key: value` creates a **key-value pair**.  Use `pair.key` to get the key, `pair.value` to get the value out of a key-value pair.

- If the `key` looks like an identifier it doesn't need to be quoted: `foo: 123` will create a pair whose key is `"foo"`
- The key can always be quoted in general or to disambiguate from other syntax elements: `"foo": 123` or `"true": 123` or `"<=": "=>"`
- To create the key from a variable or other expression, put it in parentheses: `("f" & "oo"): 123` or `(variableKey): value`
- Precedence of the `:` construct is such that it binds very tightly to the left (only the term right in front to it) and very loosely to the right (everything up to the next `,` or, of course, the next closing parenthesis/brace/bracket)
- `foo: bar: 123` is parsed as `foo: (bar: 123)`, i.e. a key-value pair whose value is another key-value pair

Interpretation of key-value pairs in different contexts:

- In numeric and boolean context, `key: value` is interpreted as `value` (completely dropping the `key`), so `123 + (foo: 456)` equals `579` and `not (foo: true)` is `false` – no need to explicitly extract the value from it.
- In string context, `key: value` is represented as the respective string representations of `key` and `value` separated by a colon, e.g. `foo: 123` becomes `"foo: 123"`
- In markup context (e.g. in `!mmm chat`), same except using the value's markup representation

If a non-key-value finds itself in a situation where it's supposed to be a key-value pair (e.g. inside braces, see below), it gets interpreted as `"": value` (empty-string key).

Structs
---
Enclosing a list of key-value pairs in braces `{`...`}` creates a **struct**. Elements of the struct can then be queried by using the normal `struct.foo` or `struct.("foo")` property lookup syntax.

- Create a struct: `{ key1: value1, key2: value2` [...] `}`
- Extend a struct: `{ struct, key3: value3` [...] `}`
- Replace a value in a struct: `{ struct, key1: value4` [...] `}`
- Deconstruct a struct into a list of its key-value pairs: `struct...` (key-value pairs ordered alphanumerically by their keys)
- Remove a value from a struct: `{ struct... where ...key ne "key1" }`

Interpretation of key-value pairs in different contexts:

- In numeric context, a struct is interpreted as the number of key-value pairs it contains.
- In boolean context, a struct is `true` if it contains any key-value pairs and `false` if it is empty
- In string and markup context, a struct is represented as corresponding representation of its key-value pairs, separated by commas, and key-value pairs ordered alphanumerically by their keys

**Comment by phylll** [comment]
Woo-hoo, exciting!

> try !mmm foreach attr in ("Finn")... in a test game near you. :)

This is `for attr`, turns out, not `foreach`, right? At least the MMM version in the test game did not recognize `foreach`.

**Comment by michael-buschbeck** [comment]
Sorry, yes, `for`, not `foreach` – nothing new on that side of the command. You're better versed in MMM syntax that I am. ;)
