### ISSUE TITLE
Reduce repeated parsing of global code

### ISSUE THREAD

**Issue by phylll** [michael-buschbeck/mychs-macro-magic#165]
(Placeholder/reminder issue)

**Comment by michael-buschbeck** [comment]
Two possible approaches:

- **Ahead-of-time parsing:** Create a separate macro that contains all `!mmm function` definitions and run it once at session start, making those functions global. Requires manual diligence (don't forget to run that macro once) or support for auto-running macros at session start (or when the first interactive `!mmm` command is received).

- **Caching:** Reference required function code every time but only parse it the first time; reuse the previously cached, parsed representation all subsequent times. Requires that MMM gains explicit support for reading and running macros (so it can choose to skip the actual reading/running of the macro if its results are already in cache). Also requires a mechanism that watches cached macros for modifications in order to invalidate the cache.

**Comment by phylll** [comment]
**Ahead-of-time parsing:** 
- *What would be the mechanism for parsing changes to the global macro library?* In case of autoparse-per-session, manual logout/login would be rather annoying for development/testing purposes (chat gets deleted, open character sheets disappear etc). In case of autoparse-on-first-MMM-command, would you build a command to trigger a "re-parse"? If the code was stored in an ability or global macro, re-running that macro could/would (?) automatically do that, right?
- *Autoparse or autorun?* I see additional use cases for an autorun feature not limited to parsing global functions, such as making sure that data exchange attributes are flushed or accumulated experience points from the last session are reset to zero (or shown to the GM to decide what to do with them). So it would make sense to me if we did not limit this feature to pre-parsing of functions alone.
- *Global variables/constants:* For operating the data exchange features via attributes on a character sheet accessible to all players, I have a bunch of global variables (fake constants). Since they are not part of a function (though they could be wrapped into one, but that would not be very convenient), they could only be centrally stored and loaded if we had autorun feature rather than just the pre-parse feature. Adding them to a global namespace would probably require something extra on MMM's part -- so maybe we'll just keep them inside the `script` blocks and don't fret over reprocessing a long list of `set` statements on every script call?
- *Per-player or per-game?* With global macros (the ones called via the `#macro` notation) we could store code for a game. But we'd be more flexible with autorun macros per player/character. Are there practical considerations from the MMM side? Is MMM confined to separate instances per player? If each player has MMM parse largely or completely the same functions, could MMM load them only once even if six autoparse/autorun macros are called?

**Caching:**
- Would caching automatically work only per macro, or could this also be implemented per function? The latter might avoid the need for extra logic to read and run macros which are only quite arbitrary containers of code, after all. (Though that logic would come in handy for other use cases, anyway, such as the critical success/failure tables.)
- Questions above re: global constants and per-player/per-game apply, as well.

The possibility of a genuine autorun feature (if it exists) would have me leaning toward autorun/autoparse rather than caching, for the moment.

**Comment by michael-buschbeck** [comment]
Leaning towards autorun is fine by me. :) I think it'll improve the user experience.

Autorun macros are regular macros, too, so you can manually re-run them any time you like. I probably wouldn't make MMM auto-re-run autorun macros when they change (oe are created during a session).

There's just a single sandbox per habe session shared by all players – MMM goes to some lengths to keep each player's data separate (by player ID, so multiple browser windows opened by the same player should be sharing the same state, and a player logging off and in again should find their previous state retained).

It wouldn't be much trouble for MMM to maintain per-player-global variables (like the existing "global" functions) or even session-global variables. The latter just poses a potential security issue: Who gets to set or overwrite what in session-global state? (GMs only? Seems sensible, but at the same time limits the usefulness of this feature.)

Idea: Session-global variables and functions can only be set by GMs **and by global functions created by GMs** – even if they're called by unprivileged players. Thinking of it, that might even be a powerful solution for "How can we allow normal players to glean some NPC state without leaking too much information?"…

**Comment by phylll** [comment]
Yup, sounds like a good solution!

**Comment by michael-buschbeck** [comment]
> Idea: Session-global variables and functions can only be set by GMs **and by global functions created by GMs** – even if they're called by unprivileged players.

Looking at the code again I've verified that this is exactly how it has been working all along: Privileges are checked based on the `playerid` stored in the executed command's `context`, which is set up at the time the command's source line is received and parsed (and then remains immutable).

So all we need now is…

- a way to set (per-player-)global variables that work just like the per-player-global functions we already support, and

- a way for GM-privileged players to "publish" variables and functions so everyone can read them.

(The term "global" shall mean "per-player-global" as opposed to "local to a script" from here on out. Session-global shall be called "public".)

I was tempted to make global variables the same way as global functions – by executing an "!mmm set" command outside an "!mmm script" block – but I think that would both be unadvisable (it might encourage writing scripts without a `script` scope; admittedly an academic concern at this point) and limiting (couldn't set global variables from within scripts or functions).

So, proposal:

- On API sandbox start, all macros following a certain naming convention (say, name starts with `MMM-Autorun`) are run automatically impersonating their respective owners.

- _!mmm_ **set global** _variable_ **=** _expression_ – to set a variable in global scope.

- _!mmm_ **publish** _name_, _name_ … – to copy the current value of one or several variables or functions into public scope. Public variables are immutable (functions too, but they are anyway), but of course they can be overwritten and replaced.

Rationale for separate "publish" step is that it that it makes it easy to separate the "prepare data" and "publish data" step – even if anything goes wrong during "prepare data" (by script design or by accident), public state will remain in its (presumably consistent) previous state.

**Comment by phylll** [comment]
> On API sandbox start, all macros following a certain naming convention (say, name starts with MMM-Autorun) are run automatically impersonating their respective owners.

What do you mean by "all macros"? Macros as in what Roll20 calls macros, i.e. those listed in the Collections tab and called using the `#macro` notation, or abilities (`%{characterSheet|ability}`), as well? I think it would be best to limit this feature to macros proper. To avoid cluttering the Collections tab, each player can limit the autorun macro's visibility to just themselves, I just checked.

Now how does that ownership of macros work? If our GM's autorun macro calls various abilities from a public character sheet that may belong to me, for example, is that code being executes as the GM's, as well? I am asking because if not, we would need to maintain a lot of important and often-changing logic in the GM's name rather than the GM just starting the ignition, so to speak, in a macro of his own.

On global/public variables or functions: How are they accessible then? Simply by their names from within any possible context (no script, script or function), I suppose, without something like the `script.` prefix? I would prefer that, despite the risks, and rather maintain some discipline over naming conventions and limiting what to set global or publish into the public namespace.

**Comment by phylll** [comment]
> all macros following a certain naming convention (say, name starts with MMM-Autorun) 

Just tested and found out that unlike attributes and abilities, macros in the Collections tab are automatically being sorted (special characters first, then uppercase A-Z, followed by lowercase a-z), and resorted when renamed.

With that, wouldn't it be both useful and on brand to have autorun macros start with `!MMM`, which would keep them at or very close to the top of anyone's macro list?

**Comment by michael-buschbeck** [comment]
> What do you mean by "all macros"? Macros as in what Roll20 calls macros, i.e. those listed in the Collections tab and called using the `#macro` notation, or abilities (`%{characterSheet|ability}`), as well?

"Proper" macros only – practical reason being that while macros have an unambiguous player-creator, abilities don't. (They're tied to a character sheet, which has one or several controller-players but no unique owner or creator.)

> To avoid cluttering the Collections tab, each player can limit the autorun macro's visibility to just themselves, I just checked.

I even thought being visible only to their creator was the default for macros. :)

> Now how does that ownership of macros work? If our GM's autorun macro calls various abilities from a public character sheet that may belong to me, for example, is that code being executes as the GM's, as well?

I assume it should be. My plan is to "execute" these macros by simply sending them to chat line by line impersonating the macro's player-creator as per #78 (requiring a fix for the still-open #148 too).

Per Roll20's docs, chat messages sent through `sendChat()` can include ability calls (but no macro calls). I expect the API to simply expand these attribute calls on a textual basis (which may well produce multiple lines of chat being sent as the result of my single `sendChat()` call) without doing anything fancy about them.

> On global/public variables or functions: How are they accessible then? Simply by their names from within any possible context (no script, script or function), I suppose, without something like the `script.` prefix?

Yes – just like global functions are simply projected into a script's variable stash. You can shadow them by setting or defining like-named variables or functions in your script, but you can't modify them short of explicitly doing `!mmm set global` and/or `!mmm publish` again.

> With that, wouldn't it be both useful and on brand to have autorun macros start with !MMM, which would keep them at or very close to the top of anyone's macro list?

Totally! I wasn't sure if what kind of naming limitations there were for macros, but if calling a macro `!mmm autorun Midgard` is a possibility, I'll be happy to go for it.

Speaking of: I'll have to define an order in which all eligible autorun macros are auto-run. I'd probably order **all** of them (across all players) alphanumerically like Roll20's UI does (case-sensitive or insensitive?) and execute them in that order. Maybe execute GMs' macros first? Or last?

**Comment by phylll** [comment]
Excellent, thanks! Indeed you're right about the default for macros being visible to the owner only.

> if calling a macro `!mmm autorun Midgard` is a possibility, I'll be happy to go for it.

I don't think spaces work, but otherwise we can run (hehe) with this.

> Maybe execute GMs' macros first? Or last?

I guess we're bound to GM first b/c the GM is the only one able to publish into the public namespace, and for now (as long as we're only populating the players' and the global namespaces with variables and functions from a reasonably consistent source) I don't see a real downside. I'd start with having the GM publish all the commonly used functions and variables, and I don't see any risks for a conflict over those as of now. *If* players will run (not just parse) anything of their own, they are likely to need some of the global variables or functions published by the GM. So if they came before the GM, they would have to autoparse those again, and we'd lose some of the performance advantage we're after.

**Comment by michael-buschbeck** [comment]
Note to self: Can probably simply stuff the entire macro text into a single `sendChat()` call. Splitting it into individual messages the Dave way Roll20 does (think `{{` `}}` pairs and the like) is nontrivial anyway.

**Comment by phylll** [comment]
Isn't that what I do all the time during testing, when I copy-and-paste an entire script with regular line breaks into the chat?

**Comment by michael-buschbeck** [comment]
I suppose it is. :) Also what Roll20 likely does when a message sent through `sendChat()` contains multi-line ability calls. It's ~turtles~ text substitution all the way to the bottom.

(By the way... it dawns on me why the docs say that `sendChat()` supports attribute calls but doesn't support macros: No fancy reason; it's simply that `sendChat()` lacks the context to know _which player's_ macro to use. Ability calls, on the other hand, are unambiguous.)

**Comment by michael-buschbeck** [comment]
Macro naming and ordering observations:

- Macro names can't contain spaces and `#` per guidance in the macro editor dialog. Pressing the space bar in the "macro name" field produces a `-` (dash).
- The macro list is sorted case-sensitively (upper-case letters precede lower-case letters).
- Multiple macros can share the same name. They remain separate in the macros list, but clicking the little "roll" icon to run any of them doesn't distinguish between the like-named macros and always runs the same macro. (Happened to be the last one on the list in my case, but that may not necessarily be always the case.)

I think I'll go with `!mmm-autorun` and/or `!mmm_autorun` macro name prefixes.

**Comment by michael-buschbeck** [comment]
Additional observation on how macros are executed: The following macro source...
```
Foo the first!
!mmm chat: Foo the second (from script)!
Foo the third!
```
results in the following chat output:
> ***Finn:*** Foo the first!
> ***Finn:*** Foo the third!
> ***Finn:*** Foo the second (from script)!

It's not a timing issue – the `!mmm chat` line gets sent to MMM, parsed, and run just as one would expect between the first and third (direct-to-chat) macro line. It rather seems that the `!mmm chat` command's `sendChat()` message is _queued_ until after the macro has been sent to chat completely.

**Comment by michael-buschbeck** [comment]
I've re-pondered syntax for "publishing variables" and "setting variables in global scope".

Both do _extremely_ similar things – they only differ which variable stash they assign to (the sandbox's shared one or the player's global one) – so I now tend towards unifying both things under the "publish" umbrella:

```
!mmm publish to sender: foo, bar, baz
!mmm publish to game: ook, meep, moop
```

This also implicitly discourages use of "global variables" as a way to avoid having to use `!mmm script` blocks, and it implicitly encourages the same best-practice behavior on per-player "global" variables as on game-scope "public" variables.

With it now becoming possible for MMM functions being called by someone who isn't their original `sender`, it becomes important that the "sender" and the "caller" of a function may be different. MMM doesn't currently support anything that gives access to a function's caller – the `sender` gets baked into the script at the time it's parsed.

However, _if_ MMM ever starts supporting an explicit `caller` (in contrast to `sender`), the `!mmm publish to` syntax above presents an obvious way to extend this feature to enable it to "publish to caller" as well.

**Comment by phylll** [comment]
> I've re-pondered syntax for "publishing variables" and "setting variables in global scope".
> Both do extremely similar things

Indeed, I had wondered the same thing about the very different approaches you had originally proposed, just never got around to questioning them. All in favor of harmonizing.

**Comment by michael-buschbeck** [comment]
I think my convoluted line of thought was something like this:

"Variables should work similar to functions… so, need a way to set variables in global scope like global functions… no, don't want top-level `!mmm set` to do that implicitly like top-level `!mmm function` does for functions… so, need to make it explicit via `!mmm set global`…"

Fun fact on the side: Neither functions nor variables need to be "global" – or as we'd say now, "published to sender" – before they can become published to the entire game. It's fine to define a bunch of script-scoped functions and then publish them to the entire game.

**Comment by phylll** [comment]
> Neither functions nor variables need to be "global" – or as we'd say now, "published to sender" – before they can become published to the entire game. It's fine to define a bunch of script-scoped functions and then publish them to the entire game.

Oh, I hadn't expected anything else. In fact, I haven't found anything among the current stuff that I would publish to sender -- I'm preparing a global init script that will simply publish all the functions and the global variables needed to manage the data exchange system between scripts to the *game*. Sender-specific publication might make sense if our magicians went into functions, or if we felt we needed to preload some code to manage the fancy feats of our personal wonder weapons. For all the general combat and health management stuff that makes for 95% of my code, however, it seems to make little sense to keep six identical copies of everything in runtime memory somewhere.
