### ISSUE TITLE
Can we manipulate whether `bar1|2|3` are shown?

### ISSUE THREAD

**Issue by phylll** [michael-buschbeck/mychs-macro-magic#200]
[SpawnDefaultToken](https://github.com/djmoorehead/roll20-api-scripts/blob/master/Spawn%20Default%20Token/0.24/SpawnDefaultToken.js) looks as if there are properties called `showplayers_bar1` etc. that determine if a bar is shown to, well, the players? A simple search for `showplayers_bar1` and then for `tokenAttributes` in the code linked up above seemed to me that was the case. Would be useful to make these properties accessible as `token.showplayers_bar1` etc., so we could very quickly provide our GM with a script to fix every selected token's bar visibility settings.

**Comment by michael-buschbeck** [comment]
MMM even _reads_ those `showplayers_barX` attributes to determine whether players should have read access to the `barX` values... and still it never occurred to me to actually make them writable (by GMs).

Seems like a simple oversight that should be easily rectified.

**Comment by michael-buschbeck** [comment]
Same goes for `showplayers_name`.

**Comment by michael-buschbeck** [comment]
For `bar1` etc. there's actually several interacting token properties:

- `showplayers_bar1`
- `playersedit_bar1` – "Allow controlling players to edit the token's Bar 1. Also shows Bar 1 to controlling players, even if showplayers_bar1 is false."
- There must also be something to control whether the bar's _numeric value_ is shown to players on top of the plain bar – not sure yet which property that might be

**Comment by michael-buschbeck** [comment]
Looks like that mysterious "something to control whether the bar's numeric value is shown to players on top of the plain bar" setting has been mystifying others as well:

https://app.roll20.net/forum/post/10330024/setting-token-bar-text-overlays-via-api

I suppose exposing something that covers `showplayers_barX` and `playersedit_barX` would still be useful for our use case.

I'm not terribly fond of the naming. Maybe `bar1_shown` and `bar1_editable` instead?

**Comment by michael-buschbeck** [comment]
Speaking of `showplayers_name`... there's actually two properties that sound like much the same thing: `showname` and `showplayers_name`. Plus, there's `playersedit_name`.

Experimentation yields this:

| `showname` | `showplayers_name` | `editplayers_name` | GMs | controllers | others
|-|-|-|-|-|-
| `false` | | | – | – | –
| `true` | `false` | `false ` | shown | – | –
| `true` | `false` | `true` | shown | shown | –
| `true` | `true` | | shown | shown | shown

**Comment by phylll** [comment]
Did you have any trouble with tokens updating properly? When I tested this new feature, the bars never behaved they way I expected them to. Sometimes the properties seemed to be updated when I checked through the Roll20 UI, sometimes not immediately. Even logging out of the game and back it did not seem to help. Sometimes one bar disappeared and the other remained, even though I had set them all to `false`.

This is the code I used:

```
!mmm script
!mmm   for tokenID in selected
!mmm     do setattr(tokenID, "bar1_shown", true)
!mmm     do setattr(tokenID, "bar2_shown", false)
!mmm     do setattr(tokenID, "bar3_shown", true)
!mmm     chat: ${tokenID.name}'s bars reset.
!mmm   end for
!mmm end script
```

**Comment by phylll** [comment]
Ah wait... sorry. All of this is only about what's shown to *players*, I just realized. So I always have to switch to player mode to see what's happening... oops.

**Comment by phylll** [comment]
> Looks like that mysterious "something to control whether the bar's numeric value is shown to players on top of the plain bar" setting has been mystifying others as well:
> 
> https://app.roll20.net/forum/post/10330024/setting-token-bar-text-overlays-via-api

Do I understand this correctly? Whether in "token bar options", "style", the radio button is set on "standard" or "compact" (= UI for whether to show or hide the numbers) is nowhere to be found in the token's visible properties as far as the API provides those? This couldn't be about the misleading label "style", as in: I could well imagine that if one of these guys in the forum looked at the JSON dump of a token's properties, they might ignore something about "style" because they associate it with design rather than functionality? Just making sure... since I don't see much of a point a GM script that will only toggle the bars correctly but won't be able to toggle the numbers atop the bars.

**Comment by michael-buschbeck** [comment]
I'll definitely expose the "compact bars" setting (probably as `bars_compact`) and, while we're at it, the "bars location" setting as well (as `bars_location`, valid values: `"overlap_top"`, `"overlap_bottom"`, or `"bottom"`).

When I was looking into the settings I've already exposed (`bar1_shown` etc.) I tried a bit of reverse engineering much like what's described in this thread: Dump values of _all_ token attributes, change something, dump again, compare. Unfortunately I couldn't find anything that changed when I manually changed the "numbers overlay" option in the UI.

This could mean:
- These UI options aren't exposed in the API (the fear shared by the folks in the thread you linked)
- My method of enumerating all API-readable attributes was flawed (I literally JSON-dumped the entire object, which includes its `attributes` property, which _appears_ to contain all attributes – certainly all that are documented)
- Changing these UI options has a _delayed_ effect on API-readable token attributes (hence why I didn't notice a difference comparing "before" and "just after")
- These UI options are reflected in the API, but not in token attributes (similar to how the players' current page overrides are stored in a `"campaign"` object attribute, but GMs' current page overrides are stored in a `"player"` object attribute)

**Comment by phylll** [comment]
> Unfortunately I couldn't find anything that changed when I manually changed the "numbers overlay" option in the UI.

Did you find a change when you changed to "compact bars"? That would be enough for my present (most basic) use case.

**Comment by michael-buschbeck** [comment]
I didn't check that setting – only the "text overlay" ones. I assume the "compact bars" setting will work fine.

**Comment by michael-buschbeck** [comment]
I may have spoken to soon: The `bar_compact` token attribute exists (defaulting to JavaScript `null` for all existing tokens) and I've reverse-engineered that its valid values are `null` (standard size) and `"compact"` (compact size)... but unfortunately even though I can set `"compact"` in API code, setting it in API code doesn't affect the visuals.

I've read about similar effects with other API object attributes. Sometimes it's possible to work around this issue by setting the attribute to some intermediate value first to trigger an update. Some further experimentation may be warranted.

Arguably good news: `bar_location` (alias `bars_location` in MMM) works (though `"overlap_bottom"` looks more like "obscure most of the token", and `"bottom"` behaves exactly like `"foo"` and looks like "vertically centered, horizontally anchored to the token center at the bars' left edge").

**Comment by michael-buschbeck** [comment]
Ah, looking into [TokenMod's source code](https://github.com/Roll20/roll20-api-scripts/blob/master/TokenMod/TokenMod.js) I'm finding…

- Valid `bar_location` values are `"above"` and `"below"` (plus the two `"overlap_`… ones) – not `"bottom"` like the docs say

- Nothing to suggest that `compact_bar` has any issues being set; I'll try TokenMod and if that works where MMM doesn't, I'll figure out why exactly from there

**Comment by michael-buschbeck** [comment]
I may have spoken too soon that I spoke too soon. `compact_bar` works _fine_ if you feed it the values it expects (i.e. `"compact"` vs `null` because why not?).

The `"above"` and `"below"` values for `bar_location` also work fine.

**Comment by michael-buschbeck** [comment]
Experimental support for the following token properties in our test game:
- `bars_compact` (boolean)
- `bars_above` (boolean)
- `bars_overlap` (boolean)

**Comment by michael-buschbeck** [comment]
I've slightly renamed the token properties (now available in our test game) – see edited previous comment. Sorry for the noise.

**Comment by phylll** [comment]
I'll ask the GM once MMM 1.35.0+ is installed in the main game, I meant to say, of course. 😀
