### ISSUE TITLE
Provide command to stop execution of script

### ISSUE THREAD

**Issue by phylll** [michael-buschbeck/mychs-macro-magic#27]
There are situations in which it would be better to be able to immediately stop execution under some condition rather than to have to either (1) wrap the entire rest of the script into a huge `if..then` block or (2) constantly repeating the same condition checks to ensure consistent output.

For example, in a ranged attack script, if I find out early that the attempted attack will fail because the distance to the target exceeds the weapon's range, it would be nice to be able to trashtalk the user, reduce ammo by whatever they wasted, and exit -- rather than going through the rest of the motion of rolling attack dice, checking success and calculating damage.

**Comment by michael-buschbeck** [comment]
Curiously enough (or not?), this might fit in well with the changes I need to do for #18 *Support async script execution*.

**Comment by michael-buschbeck** [comment]
I'll take back that last comment.

Yes, a simple "drop everything and cease working" is trivial thanks to #18, but that means that e.g. exiting out of a **combine chat** block won't even output whatever came *before* the **exit script**, which doesn't seem right.

A proper implementation will need to support explicit cooperation between nested commands.

**Comment by phylll** [comment]
Well... I do think it would not be too much to expect from script writers to design their code such that no `exit` command would be put inside a `combine chat` block, e.g. by testing for exit conditions before launching a new output pipeline. I can vaguely imagine that there might be use cases for which this would be a problem, but I can't put my finger on which ones...

**Comment by michael-buschbeck** [comment]
Okay, so, to give some context for the "already possible but awkward " label:

@phylll came up with the unhinged-genius-style suggestion to leverage an existing known (and unfortunately probably unsolvable) issue with #23, namely that roll expression syntax errors just silently (on UX level) stop the script, to work around the current lack of an `exit` command:

| Line | Command | Description
|-|-
| 1 | _!mmm_ **do** roll("over and die") | *(stop executing script at once)*
