### ISSUE TITLE
Provide access to the list of selected objects

### ISSUE THREAD

**Issue by michael-buschbeck** [michael-buschbeck/mychs-macro-magic#28]
The `msg.selected` event property contains an "array of objects the user had selected when the command was entered" (most likely tokens).

Provide access to this information in scripts – since it's a list, it probably needs *Add support for looping over tokens* #9 first. (Though I'm now wondering what the `@{selected|HP}` attribute call would do with more than one selected item.)

Selected tokens would have to be supplied as token IDs for use in `getattr()`, of course.

**Comment by michael-buschbeck** [comment]
You could always just do this though:

_!mmm_ **set** selected = "@{selected|token_id}"

**Comment by phylll** [comment]
Did you ever find a way to make this work with an actual list of selected tokens? If I do this, I only ever get the first token's id.

**Comment by michael-buschbeck** [comment]
The chat message handler gets a full-fledged "array of objects the user had selected when the command was entered" ([see docs](https://help.roll20.net/hc/en-us/articles/360037256754-API-Chat)).

It would be easy enough to expose this as an array in MMM except…

- We currently don't have an array subscript syntax, and I'm loathe to invest significantly in the crappy 1.0.0 expression engine to add one – we could easily add a poor man's subscript _function_ or _operator_ though.

- Worse, we currently have no looping construct. It's not hard to add one that simply counts from 0 to `n` though – I'd just like to keep syntactic forward compatibility to something more elaborate (like #9).

**Comment by phylll** [comment]
Thanks, it was just a clarification question to make sure I hadn't overlooked anything. Happy to either go with some workaround of my own or wait for #85 :)

**Comment by michael-buschbeck** [comment]
Version 1.17.2 has an implicit context variable called **selected** that's an array of all selected token IDs – so far, so good, but of questionable value until and unless there's a way to address individual array elements or iterate over arrays (see #9).

**Comment by michael-buschbeck** [comment]
Together with #9 that counts as a fix for providing (meaningful) access to the list of selected tokens, I reckon. Closing.
