### ISSUE TITLE
Provide access to tokens' orientation and necessary math functions for calculating arcs of vision/attack/defense

### ISSUE THREAD

**Issue by phylll** [michael-buschbeck/mychs-macro-magic#35]
Since it matters for combat actions which direction a character or NPC faces (attack from behind etc.), it would be useful for macros to have access to tokens' orientation. The Roll20 API's `token` object [offers](https://help.roll20.net/hc/en-us/articles/360037772793-API-Objects) a property `rotation` which seems to be what we need, along with basic trigonometry functions to calculate various relevant arcs.

**Comment by michael-buschbeck** [comment]
The `rotation` property is in degrees – probably a lot more accessible than radians, so I see no reason to change that aspect.

Trig functions:

- `pi` = 3.141...
- `sin(deg)` → [-1...1]
- `cos(deg)` → [-1...1]
- `tan(deg)` → [-1...1]
- `asin(x)` → [-90...90]
- `acos(x)` → [-90...90]
- `atan(x)` → [-90...90]
- `atan(y,x)` → [-180...180]

**Comment by michael-buschbeck** [comment]
The `rotation` property turns the token **clockwise** for positive values – very unorthodox from a maths point of view, but owed to the board's Y axis going downwards, which is (of course) very common in computer graphics.
