### ISSUE TITLE
#36 : Zugriff auf das Datenfeld "Gestalt" im Datenblatt zur Bestimmung von Angriffsbonus beim EW:Fernkampf

### ISSUE THREAD

**Issue by WulfricMacConuilh** [michael-buschbeck/mychs-macro-magic#36]
Bei Fernkampfangriffen kann der Abenteurer einen Bonus erhalten, wenn der Gegner bestimmte Größenangaben übertrifft. Ein Mensch mit 1,70 im Durchschnitt bekommt folgenden Bonus im Fernkampfangriff:

+4 : Gegner ist größer als 6,80 Meter, z.B. Drachen 

+2: Gegner ist größer als 3,40 Meter, z.B. Riesen

-2: Gegner ist kleiner als 0,85 Meter, z.B. Wölfe

-4: Gegner ist kleiner als 0,40 Meter, z.B. Schlangen, Ratten, Fledermäuse

Möglichkeit a: Der Spielleiter pflegt im Monsterbogen unter "Gestalt" die ungefähre Größe des Monsters

Möglichkeit b: Der Spielleiter pflegt im Monsterbogen unter "Gestalt" den Bonus, +4, +2, 0, -2, -4

**Der Bonus gilt nur für Fernkampfangriffe**. Die Größe des Gegners spielt bei Nahkampfangriffen auf Midgard keine Rolle.

**Comment by michael-buschbeck** [comment]
Das schlägt in die gleiche Kerbe wie *Provide access to enemy token's endurance (AP in German Midgard)* #19. Zugriff auf dieses Charakterblattattribut ist prinzipiell möglich (wenn man seinen Namen kennt), aber einem Nicht-GM zurzeit nicht erlaubt (und resultiert in `denied`).

Ich nehme an, dass das "Gestalt"-Attribut so wie die meisten Charakterblattattribute Midgard-spezifisch ist, d.h. es unpassend wäre, wenn ich Zugriff darauf in MMM fest verdrahte. Aber es macht natürlich komplett Sinn, gerade sowas wie "Gestalt" öffentlich zu machen ... denn das kann ja jeder Charakter sehen, der hinguckt ;)

Generische, MMM-kompatible Lösung: Der GM (bzw. allgemein: ein Spieler, der bereits Zugriff hat) kann Fremdzugriff auf beliebige festlegbare Attribute freigeben. Dann kann ein Angriffsskript wie z.B. die von @phylll das Attribut auslesen und gemäß deiner obigen Beschreibung auswerten.

**Comment by michael-buschbeck** [comment]
Oh, und zum Thema "wenn man den Attributnamen kennt" – wäre ja nicht schlecht, wenn `findattr()` auch bei Nicht-Tabellen-Attributen helfen könnte, z.B. einfach alle (Nicht-Tabellen-)Attribute auflistet, wenn man nur die Charakter-ID und einen *leeren* Tabellennamen übergibt.

**Comment by phylll** [comment]
> Möglichkeit a: Der Spielleiter pflegt im Monsterbogen unter "Gestalt" die ungefähre Größe des Monsters
> 
> Möglichkeit b: Der Spielleiter pflegt im Monsterbogen unter "Gestalt" den Bonus, +4, +2, 0, -2, -4

Ich würde für Option a plädieren, wenn "Größe" praktisch als "längste Ausdehnung" gepflegt wird, damit ein sehr langes oder breites aber nicht hohes Wesen (ein Kriechtier, eine Schlange) dann nicht fälschlich als viel kleiner verarbeitet wird als es ist. Der Bonus ist letztendlich relativ, wenn ein Riese einen Riesen angreift, gibt es keinen Bonus -- auch die Modifikatoren könnte man verrechnen, aber es scheint mir deutlich logischer, die im Spiel sichtbare Größe/Gestalt abzufragen und mit der eigenen zu vergleichen, als feste Boni im Nachhinein zu verrechnen.

**Comment by michael-buschbeck** [comment]
Hat sich mittlerweile erledigt, da die Skripte jetzt alle mit GM-Rechten laufen.
