### ISSUE TITLE
Expose turn tracker

### ISSUE THREAD

**Issue by michael-buschbeck** [michael-buschbeck/mychs-macro-magic#40]
Feeding the turn tracker with Roll20-native functionality (like `&{tracker}`) can be cumbersome. It'd be nice to get some control over it through MMM.

- Show tracker
- Clear tracker
- Hide tracker
- Add token (or custom name) with value
- Update token's (or custom name's) value.
- Remove token (or custom name) 
- Sort by name or value, ascending or descending

See the `turnorder` property on the `Campaign()` object for details ([official docs](https://help.roll20.net/hc/en-us/articles/360037772793-API-Objects#API:Objects-Campaign)).

**Comment by phylll** [comment]
Is this something you're planning on implementing? As I'm looking into our GM's request to automate critical success and failure rolls, this would be very useful to have as native MMM functionality. The big turn tracker scripts like GroupInitiative and InitiativeTrackerPlus don't provide what we would need; the only thing I found that lets every player add custom items to the tracker and that I actually got to work is a dirty hack by TheAaron called ACT (https://app.roll20.net/forum/permalink/3346527/, running in our TEST game), but without removal functionality, updating of values, or linking to token markers.

**Comment by michael-buschbeck** [comment]
Requires #159

**Comment by michael-buschbeck** [comment]
We may also want some customizable sorting facility for this.

**Comment by phylll** [comment]
How does the turn order process or reflect the switch from one round to the next? The API docs you linked up above didn't help me figuring this out. I'm asking because for https://github.com/phylll/mychs-macro-magic/issues/3, I need a few events. Most are within the run time of my combat scripts, but we'll need one event at the change of turns (technically, at the end of each turn). Of course, it would be fancy to have that event automatically triggered when the GM ends a turn and starts a new one ... though, on second thought, there is usually so much trouble with the turn tracker that it may not be a good idea to slave anything with serious consequences (loss of life/health points at end of turn) to it, and better to ask the GM for a separate click on a macro button to confirm that a turn has actually ended and all the remaining effects should be processed. What do you think?

Even in the latter case, it would still be quite nice for MMM scripts to be able to reflect key transient effects (Yorric is unable to attack for `1d6` rounds because there is this really nasty itch he's got to scratch. Next time, don't skip bathing day!).

**Comment by michael-buschbeck** [comment]
Love the idea of showing character state in the turn tracker, fed by scripts. (Note: In rows connected to a token on the table, the name column is fixed to the token's name and only the rightmost column can be freely customized.)

I don't think there's a specific API event connected to the start of a round. I don't even think there's the actual concept of a "round" in Roll20 – as far as I can tell the turn order window is nothing but a mildly glorified table display with little in the way of specific gane support.

I don't really know what our GM is doing in order to rotate entries in the turn order table – but MMM could subscribe to a (generic) event that fires when the `turnorder` property changes and try to figure events out by comparing old vs new value (both given to the event handler).

Quite frankly, I think we'll do better taking complete control of the turn order window as an output device and leaving high-level concepts like a "start of round-based combat", "start of a new round in combat" to scripts.

**Comment by phylll** [comment]
> Quite frankly, I think we'll do better taking complete control of the turn order window as an output device and leaving high-level concepts like "start of round-based combat", "start of a new round in combat" to scripts.

Agree.

**Comment by michael-buschbeck** [comment]
That said, as discussed on Discord:

It might be nice if we didn't have to summarily equip existing Roll20 turn order UI with a big "DO NOT TOUCH" sign but could instead integrate it into our scripts' UI.

Our GM reports there's at least one "advance to next player" button of sorts. MMM could capture that event by subscribing to the generic `change:campaign:turnorder` event callback and figure out whether this button was pressed by simply comparing new to prev state (both passed to the handler by Roll20), and then somehow forward the event to custom script code to handle – details of how that could work TBD (maybe call a custom global MMM function published under a certain well-defined name?).

**Comment by michael-buschbeck** [comment]
UI ways for GMs to modify the turn tracker:

**Open the turn tracker** by clicking the ![image](https://user-images.githubusercontent.com/5649035/161422155-0d85fa85-c53c-45d1-b705-66dc464d3337.png) button in the toolbar.

**Add entries from tokens** by selecting them and then selecting "Add Turn" from the context menu – this can be done multiple times:
![image](https://user-images.githubusercontent.com/5649035/161422203-79cc8637-35f4-462a-a80f-4baf8a35155d.png)

**Delete individual entries** by clicking the trashcan icon on hover:
![image](https://user-images.githubusercontent.com/5649035/161422233-08897e64-268c-43c8-b4b3-0728bf3f4cb9.png)

**Move entries** by dragging them (the mouse cursor becomes a four-way arrow on hover).

**Rotate entries** (move first entry to bottom, second entry to first) by clicking the ![image](https://user-images.githubusercontent.com/5649035/161422286-752dca42-9769-458a-9e73-d7024699fbda.png) button at the bottom right of the tracker window.

**Sort entries** in various ways, **delete all entries**, or **add user-defined entries** by clicking the ![image](https://user-images.githubusercontent.com/5649035/161422346-80c74868-6943-472a-bac6-6497ed0ecc1b.png) button at the bottom right of the tracker window, which opens this dialog box:

![image](https://user-images.githubusercontent.com/5649035/161422372-eea4cf1e-4153-41e0-9318-4a0f38051b33.png)

Notice the "Round Calculation" ("Runde Berechnen") at the bottom, which [is documented](https://help.roll20.net/hc/en-us/articles/360039178634-Turn-Tracker#TurnTracker-AddingaCustomItem) to work as follows:

> Optionally you can add a **Round Calculation** to custom items. These calculations are completed every time the custom item reaches the top of the Turn Tracker. This is particularly useful for setting up a "Round Count" object that increases by one every rotation, or setting depreciating buffs that decrease every round. For example, entering "+1" will increase the value at the start of every turn, while "-1" will decrease the value by 1 at the start of every turn (useful for tracking things like buffs or other temporary conditions).

**Close the turn tracker** by clicking the ![image](https://user-images.githubusercontent.com/5649035/161422534-01a36900-c9d4-405f-94ca-3c785f45ea24.png) button in the upper right corner. The tracker retains state between being closed and opened again.

**Comment by michael-buschbeck** [comment]
I can't quite see an API method to show or hide the turn order window, unfortunately.

**Comment by michael-buschbeck** [comment]
Assorted thoughts:

- I wonder if the value entered for the "round calculation" field shows up anywhere in the API-exposed `turnorder` JSON data structure. (It's not documented at all, but we know how little that means.)

- It seems plausible that I should be able to create individual script hooks for each of the tracker-changing GM UI interactions listed above. I can't prevent the change from happening, but I could make it easy for the script to immediately restore the original state: I'd pass the original tracker state to the script so it could easily restore it (or perform whatever _custom_ modification it would like to do based on the _original_ start prior to updating the turn tracker on its own terms).

**Comment by michael-buschbeck** [comment]
The "customizable sorting facility" is now an `order` operator that works like this:

| Line | Commands | Result
| ---- | -------- | ------
| 1    | _!mmm_ **set** sorted = (-2, -7, 2, 7, 5) **order** (...left < ...right) | sorted = (-7, -2, 2, 5, 7)
| 2    | _!mmm_ **set** reverse = (-2, -7, 2, 7, 5) **order** (...left > ...right) | reverse = (7, 5, 2, -2, -7)
| 3    | _!mmm_ **set** pairs = (foo: 456, foo: 123, bar: 123) **order** (...left.key **lt** ...right.key, ...left.value < ...right.value) | pairs = (bar: 123, foo: 123, foo: 456)

It comes with new `lt`, `le`, `ge`, and `gt` string relation operators that had been mysteriously absent until now. (I might also need to add something like `lower(str)` and `upper(str)` to facilitate case-insensitive comparison.)

**Comment by michael-buschbeck** [comment]
> I can't quite see an API method to show or hide the turn order window, unfortunately.

But there is! The `Campaign` object also has `initiativepage`, which stores the "ID of the page used for the Turn Tracker when the turn order window is open. When set to `false`, the turn order window closes", plus guidance to keep this in sync with the `playerpageid` "or you may end up with strange results".

**Comment by michael-buschbeck** [comment]
Test game has 1.29.0-pre-20220405-2140 with `showtracker(bool)` to show or hide the tracker window. `showtracker()` without an argument just returns the current state of the tracker window. Baby steps, but it works!

**Comment by michael-buschbeck** [comment]
> * I wonder if the value entered for the "round calculation" field shows up anywhere in the API-exposed `turnorder` JSON data structure. (It's not documented at all, but we know how little that means.)

Well, yeah. This is what the JSON can look like in actual life:

```javascript
[
    {
        "id": "-1",
        "pr": 1,
        "custom": "Round",
        "_pageid": "-MRZtlN_1XJe4kQl3IaM",
        "formula": "+1"
    },
    {
        "id": "-MS7Zuq-JXiICokyWIq5",
        "pr": "0",
        "custom": "",
        "_pageid": "-MRZtlN_1XJe4kQl3IaM"
    },
    {
        "id": "-1",
        "pr": "0",
        "custom": "Custom entry",
        "_pageid": "-MRZtlN_1XJe4kQl3IaM"
    }
]
```

To wit:
- `"id"` is a token ID or `"-1"` – notice not `-1` the number, `"-1"` the string
- `"pr"` is the value shown in the right-hand column – anyone's guess what "pr" stands for
- `"custom"` is the title for entries where `"id"` is `"-1"` – title implied for entries connected to a token (the token's name)
- **undocumented:** `"_pageid"` seems to be the current page, same as `Campaign().get("playerpageid")`
  - Perhaps the page containing the token? (The token object has a `"_pageid"` property, so this is cached or redundant.)
  - Perhaps the entries shown in the tracker are filtered to only show those on the current page? (Note that different players can simultaneously be on different pages – see `Campaign().get("playerspecificpages")`.)
- **undocumented:** `"formula"` seems to be whatever was entered in the "Round Calculation" field for custom entries.

**Comment by phylll** [comment]
I did wonder about this some time ago where I thought it might be handy to work with a `playerid` or be able to whisper to a player rather than trying to figure out which character belongs to the right player. I was able to implement whatever I worked on without anything like that, but I can imagine exposing the player could come in handy in the future.

**Comment by michael-buschbeck** [comment]
Noted!

By the way, `playerid` already exists as a context variable (of questionable value without anything else to support it, I suppose).

**Comment by phylll** [comment]
Indeed, I had found that.

**Comment by michael-buschbeck** [comment]
Trial-and-error insight: Even though `"formula"` is not exposed in the Roll20 UI for token-based entries, it works just as well with token entries as with custom entries. (Not sure if that makes it measurably more useful.)

**Comment by michael-buschbeck** [comment]
Trial-and-error insight: `"formula"` supports **exactly** inputs that start with `+num` (e.g. `+1`) or with `-num` (e.g. `-2`). Anything else after that is ignored (e.g. `+3+1` works the same as `+3`). Anything not following that format yields the error message "The turn order calculation ... is invalid." in the chat window.

**Comment by michael-buschbeck** [comment]
Okay, the test game now has MMM 1.29.0-pre-20220406-1950 with somewhat seemingly complete implementations of...

...the `showtracker()` function:
- `showtracker(true)` – show the turn tracker window (and return `true`)
- `showtracker(false)` – hide the turn tracker window (and return `false`)
- `showtracker()` – return the current visibility state of the turn tracker window (`true` or `false`)

...the `gettracker()` function:
- Returns a (potentially empty) list of structs, each struct describing one entry, in the displayed order
- Struct keys:
  - `token` – associated token ID or `unknown` if entry is not associated with a token
  - `title` – title of the entry in the left-hand column (token name or custom)
  - `value` – value of the entry in the right-hand column
  - `formula` (optional) – formular applied to the entry value when it becomes the first entry as the GM clicks the "next" button

...the `settracker()` function:
- Replaces the contents of the turn tracker with the given list of entries given as structs (see above)
  - For token-associated entries, only `token` has to be passed in, and it can be either a token ID, token name, character ID, or character name (as per usual for MMM)
  - For custom entries, only `title` has to be passed in (...and technically not even that; you'll get an empty entry if you pass in an empty struct)
 - Examples:
   - `settracker()` clears the tracker
   - `settracker({token: "Finn"}, {token: "Yorric"})` fills the tracker with Finn's and Yorric's entries
   - `settracker(selected select {token: ..., value: 0})` fills the tracker with all selected tokens
   - `settracker({title: "Round", value: 1, formula: "+1"}, gettracker())` prepends a round counter to the current tracker

**Comment by michael-buschbeck** [comment]
To add:
- `showtracker()` without argument and `gettracker()` are unprivileged functions that can be used by any player
- `showtracker(bool)` and `settracker(entries)` require GM privileges

**Comment by michael-buschbeck** [comment]
Some investigation into `initiativepage`, the per-entry `_pageid`, and who sees what, when:

- The turn tracker window is always visible to either everyone or no one. (There is no way to show the window to just a subset of players.)
- Turn tracker visibility is completely controlled by whether `initiativepage` is `false` or anything else. If anything else, everyone sees the window.
- GMs always see all entries regardless of the entry's `_pageid`. There's no UI indication that entries might be on different pages.
- Players only see entries whose `_pageid` matches `initiativepage`. All players always see the same entries, regardless of which page each individual player is on at the time (cf. `playerspecificpages`).
- Roll20 manages `initiativepage` automatically… and buggily (or maybe just "non-intuitively") because it can happen that `initiativepage` gets out of sync with `playerpageid`.

What's the "currently viewed page"?
- A given player's current page can be gleaned from `playerspecificpages` falling back on `playerpageid`.
- A given GM's current page can be read from the GM's `"player"` object's read-only `_lastpage` property. This information is only valid if `playerIsGM()` is `true`.

Open points:
- What's the initial value of `initiativepage` when the turn tracker gets opened through UI? (I'm guessing it's the GM's currently viewed page.)
- What entries are affected by the "next" button? (I'm assuming all.)

To make `settracker()` useful I'll have to expose `_pageid` as a per-entry `page` property, introduce a public `getpage()` function (returns the calling player's or GM's current page), and for good measure introduce a new read-only `page` property for tokens.

**Comment by michael-buschbeck** [comment]
Per these observations, slight amendment of plans:

- Each entry's native `_pageid` is exposed as a property named `page` in the per-entry struct.
- `gettracker()` called by GMs returns all entries regardless of `initiativepage` (even if the window is hidden).
- `gettracker()` called by regular players returns all entries whose `page` is equal to the current `initiativepage` – i.e. those currently visible to the player. If the tracker window is hidden, an empty list is returned.
- `settracker()` (only available to GMs) always replaces all entries.
- `settracker()` ignores `page`, just like `title`, for any entry that has a valid `token` (and she' always uses the token's page).
- `showtracker()` without arguments called by GMs returns the current `initiativepage` if the tracker window is shown or `undef` if not. These values are intuitively interpreted as `true` or `false`, respectively, in boolean context.
- `showtracker()` without arguments called by regular players returns `initiativepage` if that's the player's current page, or `"other"` if it's any other page, or `undef` if the tracker window is closed.
- `showtracker(arg)` (only available to GMs) hides the tracker window if `arg` coerces to boolean `false` (this includes passing `false` or `""`), or shows it set to a specific page if `arg` is a valid page ID, or to the GMs currently viewed page if it's anything else (including plain `true`).

**Comment by michael-buschbeck** [comment]
Recent change?:

Despite [documentation to the contrary](https://help.roll20.net/hc/en-us/articles/360037772793-API-Objects#API:Objects-Campaign), it seems like `initiativepage` is actually now either `false` (hide tracker window) or `true` (show tracker window), never any page ID at all.

Clicking the ![](https://user-images.githubusercontent.com/5649035/161422155-0d85fa85-c53c-45d1-b705-66dc464d3337.png) button sets `initiativepage` to `true`.

Players see whichever entries have a `_pageid` that matches the page they're currently viewing – players on different pages may see different entries.

**Comment by michael-buschbeck** [comment]
More recent change, apparently:

- Non-token entries are displayed to all players regardless of which page they are on. `_pageid` is ignored – non-token entries are displayed even to players on other pages.
- Token entries require `_pageid` and are only displayed to players on that page. (In effect, `_pageid` caches the token's corresponding property. If `_pageid` is missing, the corresponding token entries are displayed nowhere to players.)
