### ISSUE TITLE
Support simpler script customization/localization

### ISSUE THREAD

**Issue by michael-buschbeck** [michael-buschbeck/mychs-macro-magic#47]
We're entering an age of reusable, customizable MMM scripts – scripts that are getting maintained (@phylll) and used by different parties. (I'm loving it!)

When users customize chat messages and a new version of the script is released by the maintainer, all customizations have to be either redone or very carefully migrated. Conventions like having all customizable settings as variable assignments in a header block can mitigate the issue, but that's still cumbersome to maintain, even more so if the goal is to make a whole lot of chat messages customizable.

Add support for simpler script customization/localization. Since we're completely in control of the language and its syntax, make its integration as painless as possible to use.

**Comment by michael-buschbeck** [comment]
Ultimately I'd love to be able to do this as a party:
- GM keeps authoritative version of script as a Roll20 macro, named e.g. `MMM_Melee_Attack`
- GM shares that macro with the entire party. (This makes the macro-script available to all players, but players can't edit it.)
- Player creates their own macro that...
  - Starts with a customization block (defining values for all customizable settings and any or all customizable chat messages)
  - Continues with a vanilla Roll20 `#MMM_Melee_Attack`-style reference to the reusable MMM script/macro.

Roll20's simplistic replace-repeatedly-until-nothing-left-to-replace paradigm of macro execution might just work in our favor here :)

How it might look from a player's point of view:
```
!mmm customize
!mmm     set weaponName = "Claymore"
!mmm     set verbose = true
!mmm     chat [attack_pre]: /me swings his Claymore with elegance, as if it was weightless.
!mmm     chat [attack_success]: And it's a hit! $[damage] points of damage.
!mmm     chat [attack_failure]: And he misses.
!mmm end customize
#MMM_Ranged_Attack
```

And the corresponding `MMM_Melee_Attack` script, excerpts:
```
!mmm script
!mmm     expect weaponName
!mmm     expect verbose = false
...
!mmm     chat [attack_pre]: /me attacks with ${weaponName}.
!mmm     if attackRoll >= 20
!mmm         chat [attack_success]: Attack successful. $[damage]{roll(1d20) + getattr(... blah blah ...)} damage.
!mmm     else
!mmm         chat [attack_failure]: Attack failed.
!mmm     end if
...
!mmm end script
```

Things to note:
- Variables that **must** be customized are defined with `expect` rather than `set`. You can define a default value with `expect` but don't have to. If an `expect` variable that doesn't have a default isn't customized before the script is run, the user gets an error message and the script doesn't run.
- Chat messages that are customizable have an extra `chat [label]:` that can be referred to if the user wants to customize that message. In the same vein, calculated parts of the chat message have `$[label]{...expr...}` to allow users to use them in their customized messages. (Those expression labels are scoped to the chat line and can't be used elsewhere.)

**Comment by michael-buschbeck** [comment]
Slight refinements of the above design:

I've realized that overloading **chat** depending on context (within our outside of a **customize** block) to both output chat *and* define translations for chat messages, while "elegant", adds unnecessary cognitive load on the user. Better to introduce a separate command to provide translations, e.g. **translate**.

(Plus, the **translate** meaning of **chat** wouldn't make sense within a **combine chat** block, and enforcing that by error message would be confusing.) Note that **set** isn't as overloaded: It means "set a variable" in any context.

So we'd get:
```
!mmm customize
!mmm     set weaponName = "Claymore"
!mmm     translate [attack_pre]: /me swings his Claymore with elegance, as if it was weightless.
!mmm end customize
#MMM_Ranged_Attack_Script
```

Also, it should be possible to *nest* **customize** blocks – e.g. an inner, indirectly referenced one that provides default localization into German into an outer one that provides additional per-user customizations:
```
!mmm customize
#MMM_Ranged_Attack_Localization_DE
!mmm     set weaponName = "Langschwert"
!mmm     translate [attack_pre]: /me schwingt sein Langschwert mit meisterhafter Eleganz.
!mmm end customize
#MMM_Ranged_Attack_Script
```

...where the `MMM_Ranged_Attack_Localization_DE` macro would provide its own **customize** block that only contains **translate** commands that translate chat output from the original English into German.

In any case:
- The outermost **end customize** commits all customizations from the **customize** block's variable stash to the player's context. Any error within the **customize** block means this won't happen, like with **script** blocks.
- Customizations present in the player's context will be picked up (and removed from the player's context) by the next complete top-level MMM command – typically a **script** block (of the script the customizations were intended for). But this goes for any complete top-level command, regardless of whether it wants or needs the customization.

On the script writer's side, it certainly remains important that the script writer gets to control which variables can and cannot be overwritten by customization – but it's not necessary to introduce a whole new command (like **expect**) for that. Adding a qualifier to the existing **set** command should be sufficient:

```
!mmm script
!mmm     set customizable weaponName
!mmm     set customizable verbose = true
...
!mmm end script
```

**Comment by michael-buschbeck** [comment]
The last missing piece is how to enable players to get a *template* of allowable customizations and translations:
```
!mmm save customization template Michael_Claymore
```
...then simply run the attack script. Instead of executing it'll save the following text in a new macro named `Michael_Claymore`:
```
!mmm customize
!mmm     set weaponName =
!mmm     set verbose = false
!mmm     translate [attack_pre]: /me attacks with $[weapon].
!mmm     translate [attack_success]: Attack successful. $[damage] damage.
!mmm     translate [attack_failure]: Attack failed.
!mmm end customize
```
If the script already had prior customizations, those replace the defaults that are written out;
```
!mmm customize
!mmm     set weaponName = "Claymore"
!mmm     set verbose = true
!mmm     translate [attack_pre]: /me schwingt sein Langschwert mit meisterhafter Eleganz.
!mmm     translate [attack_success]: Attack successful. $[damage] damage.
!mmm     translate [attack_failure]: Attack failed.
!mmm end customize
```
That way players can easily and incrementally play along with script updates: When they see that there's a yet-untranslated message, they can just dump a new version of their customization script and selectively customize whatever was added by the script author.

If, however, the player went complicated, rearranged commands or even added conditionals etc. in their **customize** block – which is valid, of course – those commands won't be represented. That could even be used as a feature to make *generic* parametrizable customization template generation scripts.

(The `save customization template` command is unwieldy and tentative. Just needed something for exposition here.)

**Comment by michael-buschbeck** [comment]
It just occurred to me that I've illustrated everything here by way of customizing a ***ranged* attack script* for a *Claymore*, and done so with great conviction.

Well, a Claymore is a rather sizable sword. Therefore, swinging it counts as a ranged attack among swordsmen. Right? Right.

**Comment by phylll** [comment]
With great `strength`, who says you couldn't throw a claymore? Like, say, throwing a statue?

**Comment by michael-buschbeck** [comment]
Completely agreed with the strength dependency of ranged Claymore attacks. Should be a house rule.

> Also, it should be possible to *nest* **customize** blocks – e.g. an inner, indirectly referenced one that provides default localization into German into an outer one that provides additional per-user customizations:

The rationale is solid but allowing **customize** blocks to nest makes their state-reset guarantees really awkward to explain.

It's easier to allow them to *stack*, one after another, until there's a non-**customize** command to apply the customizations to.

With that:

- Like **script**, every **customize** block must be top-level. If it's not, the prior pending state will be considered abandoned and is reset.

- Any parse or execute error in a **customize** block invalidates that particular **customize** block but nothing else – all other **customize** blocks in the stack and the customized script at the bottom of the stack remain valid (...in their own right).

**Comment by michael-buschbeck** [comment]
Documentation:
- [_!mmm_ **customize**](https://github.com/michael-buschbeck/mychs-macro-magic#mmm-customize--end-customize) block – includes overview and extended example
- [_!mmm_ **set customizable**](https://github.com/michael-buschbeck/mychs-macro-magic#mmm-set-customizable-variable) command
- [_!mmm_ **chat [**<span>_label_</span>**]**](https://github.com/michael-buschbeck/mychs-macro-magic#mmm-chat-label-template) variant of **chat** command
- [_!mmm_ **translate [**<span>_label_</span>**]**](https://github.com/michael-buschbeck/mychs-macro-magic#mmm-translate-label-template) command
- [_!mmm_ **customize export**](https://github.com/michael-buschbeck/mychs-macro-magic#mmm-customize-export-to-destination) command
