### ISSUE TITLE
TypeError during execute of `set` command

### ISSUE THREAD

**Issue by michael-buschbeck** [michael-buschbeck/mychs-macro-magic#65]
@phylll reports having encountered this error:

> (From Mych's Macro Magic):
> During execute, TypeError: Cannot read property 'replace' of undefined in expression in script: !mmm set damageRoll = ❌roll(weaponDamageExpr)

...possibly related to setting variables in a **customize** block that don't even exist in the script. The reported location of the error may be spurious.

https://discord.com/channels/751494699679875240/805542051793731616/813860282463289364

**Comment by phylll** [comment]
The same error message also appears when I try to execute an `if..then` block inside a `customize` block, at the same -- seemingly unrelated -- line of the main script:

> During execute, TypeError: Cannot read property 'replace' of undefined in expression in script: !mmm set damageRoll = ❌roll(weaponDamageExpr)

What I did is the following, without masking the `if` and `end if` lines as comments:

```!mmm   set weapon = ?{Choose wisely, or die!|Dolch, Dolch | Kurzschwert, Kurzschwert | Langschwert, Langschwert}
!rem   if weapon eq "Langschwert"
!mmm   set cWeaponLabel = "Feuer (Langschwert)"
!mmm   set cWeaponName = "Feuer"
!mmm   set cWeaponType = "Langschwert"
!rem   end if```

This code, without the conditional block, works well. With the conditional block, it throws the above error.

**Comment by michael-buschbeck** [comment]
Thanks for the data point, and sorry for the tardiness – I'll get to it soon!

*(starts looking for the cat)*

**Comment by michael-buschbeck** [comment]
There's a script bug in the snippet above that may have this error (which definitely is an MMM bug!) as a knock-on effect: This...
```
!mmm   set weapon = ?{Choose wisely, or die!|Dolch, Dolch | Kurzschwert, Kurzschwert | Langschwert, Langschwert}
```
...will look like this after Roll20 has completed substituting the query result into the line:
```
!mmm   set weapon = Langschwert
```
...but it should look like this:
```
!mmm   set weapon = "Langschwert"
```
Since there's probably no variable named `Langschwert` (or `Kurzschwert` or `Dolch`) in the script, that means that `weapon` is assigned an undefined value, and ultimately (possibly through a chain of lookups that fail due to the undef-ness of `weapon`) some later script command attempts to do something with an undef-valued variable that makes MMM call `replace()` on the variable's value, which then leads to the `TypeError`.

MMM should, of course, just do what it normally does when faced with error conditions during evalutation: just return undef and soldier on, not run into a JavaScript error and propagate that up to the user.

(I wonder if introducing an explicit "undef" return value in the spirit of the existing `default` and `defined` special values – and a corresponding `isdefined()` function – might be a good idea?)

**Comment by michael-buschbeck** [comment]
> (I wonder if introducing an explicit "undef" return value in the spirit of the existing `default` and `denied` special values – and a corresponding `isdefined()` function – might be a good idea?)

In the same spirit... @phylll, do you think it would be useful to have an (opt-in) mode that throws a hard execution error when attempting to read a variable that hasn't been **set** before? (Like Python does it, more or less.)

**Comment by phylll** [comment]
Thanks for the explanation - I had since abandoned this approach with the dropdown for other reasons, but good to know about the problem with non-numerical values!

The problem with this MMM error definitely happens also without this `set weapon=?{...}` line. 

On throwing a hard execution error: well, it would make debugging easier, yes, and I've been trying to initialize everything so yes, if it's easy to do on your end. Since this is helpful only for a particular class of bugs/problems, I don't think it's worth investing a lot of time either.

**Comment by phylll** [comment]
Ah, something else: last night I also found that just executing the main script, without the preceding `customize` block, threw this MMM error (I believe). That should not happen, should it? As I understood it, the script works standalone with all its defaults if there is no `customize` block before it, no? And I think it worked a few days ago... so maybe I added something within the script that works only with the `customize` block but not without it, which seems like something that I should not have been able to do.

**Comment by michael-buschbeck** [comment]
> Ah, something else: last night I also found that just executing the main script, without the preceding `customize` block, threw this MMM error (I believe). That should not happen, should it? As I understood it, the script works standalone with all its defaults if there is no `customize` block before it, no?

The JavaScript `TypeError` bubbling up to you is unacceptable, of course – something else should happen.

It'd be typical for MMM that this "something else" would be "return undef and carry on" – which might be the reason the script worked before where it now crashed due to that JavaScript error bubbling up.

**Comment by phylll** [comment]
But just to be sure: if my script is free of bugs, it should execute fine without a `customize` block, right? The entire customization is designed as optional, as far as I understand?

**Comment by michael-buschbeck** [comment]
Absolutely – assuming all your **set customizable** have defaults (but if they don't, you'd get a very specific and distinctive error message) and, of course, those defaults are reasonable enough for the script to behave reasonably when using them (which I assume they are).

The only (by-design) way to make a script that _requires_ a **customize** block is to have at least one **set customizable** _without_ default value. (Actually, to _execute_ one such **set customizable** – it'd be fine if it was in a branch that never gets executed, so you could e.g. have required customizations based on another setting.)

**Comment by michael-buschbeck** [comment]
Is it plausible that in the reported line...

> (From Mych's Macro Magic):
> During execute, TypeError: Cannot read property 'replace' of undefined in expression in script: !mmm set damageRoll = ❌roll(weaponDamageExpr)

...the `weaponDamageExpr` variable could have been undefined if `weapon` was undefined due to the script bug described above?

(I've just discovered that calling `roll(undef)` causes this exact "TypeError" to bubble up. Of course, `roll(undef)` should instead just return `undef`.)

**Comment by phylll** [comment]
Ja, stimmt. Nicht wegen _des_ anderen Script-Bugs (meintest du den mit dem `?{...}`-Aufruf? Gibts nicht mehr), aber wegen einer Änderung der Defaults.

Ohne `customizable`-Block wird

`set weaponDamageExpr = getattr(sender, findattr(sender, "Angriff", "Waffe", cWeaponLabel, "WaffeSchaden"))`

mit einem cWeaponLabel aufgerufen, das es bei Yorric nicht gibt ("Dolch"), deshalb gibt dann wahrscheinlich findattr() und in der Folge getattr() undef zurück. Kann das der Grund sein?

**Comment by phylll** [comment]
So I left this default bug in the script version installed in the TEST game, but I fixed it in our wiki (at least for Yorric, or anyone who has a "Kurzschwert" as a reasonable default weapon).

I will add a plausibility check and stop execution if the chosen (or default) weapon does not exist. But how do I check for this problem? `undef` does not seem to be evaluated as `false`, `0` or `""` in this code (I tried all of these, nor does there appear to be a constant `undef` to which I could compare my variables):

```!mmm   set ownName = getattr(sender, "token_name")
!mmm   set effAttack = getattr(sender, findattr(sender, "Angriff", "Waffe", cWeaponLabel, "WaffeEW"))
!mmm   set weaponDamageExpr = getattr(sender, findattr(sender, "Angriff", "Waffe", cWeaponLabel, "WaffeSchaden"))
!mmm   set weaponDamageBonus = getattr(sender, findattr(sender, "Angriff", "Waffe", cWeaponLabel, "WaffeEfSchB"))
!mmm   if not (effAttack) or not (weaponDamageExpr)
!rem     // cWeaponLabel does not exist, so key values are undefined and the script cannot work
!mmm     chat [WeaponNotFound]: $[me]{ownName} does not have a weapon with the label "$[weaponLabel]{weaponLabel}".
!mmm     exit script
!mmm   end if```

**Comment by michael-buschbeck** [comment]
Never mind the language – I might have read your comment and not noticed it wasn't English until later :P

Yes, that seems plausible. I guess that means the `roll(undef)` bug is what was causing this then.
