### ISSUE TITLE
Possible bug in pulling rolls with $[[0]] from Roll20

### ISSUE THREAD

**Issue by phylll** [michael-buschbeck/mychs-macro-magic#88]
OeGStefan noticed some weird behavior.

Compare the following two scripts.

This one counts a `6` for the `1d20` roll as a critical success, which is wrong:
```
&{template:none} [[1d20]] {{}}
&{template:none} [[1d6]] {{}}
!mmm script
!mmm set first = $[[0]]
!mmm set second = $[[1]]
!mmm if iscritical(first)
!mmm     chat: Kritisch: ${first}
!mmm else
!mmm     chat: Unkritisch: ${first}
!mmm end if
!mmm end script
```

This one does it correctly:
```
&{template:none} [[1d20]] [[1d6]] {{}}
!mmm script
!mmm set first = $[[0]]
!mmm set second = $[[1]]
!mmm if iscritical(first)
!mmm     chat: Kritisch: ${first}
!mmm else
!mmm     chat: Unkritisch: ${first}
!mmm end if
!mmm end script
```

Should there be any difference in MMM's behavior? Is this possibly pointing at a bug in `iscritical()` and, potentially, `isfumble()`?

**Comment by michael-buschbeck** [comment]
`$[[0]]`, `$[[1]]` and so on refer to the most recent chat message that contained an inline roll.

In the first example, that would be the `[[1d6]]` message. By the time the first _!mmm_ command is received, the `[[1d20]]` result (stored in `$[[0]]` immediately after that line) has already been overwritten by the `[[1d6]]` result (also stored in `$[[0]]`). `$[[1]]` remains nonexistent in the first example.

So what happens is that `[[1d20]]` gets rolled and discarded, `[[1d6]]` gets rolled and assigned to `first` (where a rolled `6` is a critical success, of course), and `second` is assigned an undefined value.

(I could perhaps make referencing a nonexistent variable resolve to `unknown` with a hint like "Variable $[[1]] referenced before assignment" to nahe this easier to diagnose.)

**Comment by phylll** [comment]
Hm. I should've written out the output. In both examples, `$[[0]]` delivers the `[[1d20]]` roll and `$[[1]]` delivers the `[[1d6]]` roll. The only thing that differs is the evaluation of `iscritical()`.

**Comment by phylll** [comment]
Oh, wait. Sorry. I am **100%** sure that it worked that way in OeGStefan's long magic script. But in this test case, it doesn't.

**Comment by phylll** [comment]
And the second example "works" because there, it is not the first but the second roll (`[[1d6]]`) that is being discarded. So Roll20 discards any inline rolls after the first in the same line before MMM even sees them?

**Comment by michael-buschbeck** [comment]
The second example is completely fine: `[[1d20]]` is rolled and stored in `$[[0]]`, `[[1d6]]` is rolled and stored in `$[[1]]` – both `$[[0]]` and `$[[1]]` remain available until the next line containing an inline roll (or roll) is encountered, so `first` eventually gets the `[[1d20]]` result and `second` gets the `[[1d6]]` result.

Roll20 doesn't remember or discard anything – MMM keeps track of inline roll results. It doesn't really make sense for MMM to store more than the latest inline rolls' results because... where does it end? MMM has no idea how many recent chat messages that contain inline rolls might be intended as part of the script's execution.

**Comment by phylll** [comment]
Ah, so my misunderstanding was from whether MMM discards the previous *roll* or the previous *chat message* that contains 1-n rolls. If we always have access to the last chat message with *all* its rolls stored in `$[[0,1,2,...,n]]` -- all good.

**Comment by michael-buschbeck** [comment]
Yup, that describes it perfectly. :)
